// KacikanLabs catalog - all course labs organized by year, course, and date
window.KACIKANLABS_LABS = [
  {
    year: "2026",
    course: "CENG113M",
    labDate: "LAB 1",
    title: "Lab 1",
    description: "Introductory lab PDF for CENG113M.",
    tags: ["pdf", "intro"],
    assets: [
      { label: "LAB1.pdf", kind: "pdf", href: "assests/2026/CENG113M/LAB1/LAB1.pdf" },
    ],
  },
  {
    year: "2026",
    course: "CENG113M",
    labDate: "LAB 2",
    title: "Lab 2",
    description: "Practice exercises and slides for CENG113M Lab 2.",
    tags: ["python", "slides"],
    assets: [
      { label: "CENG113M_Lab2.pptx", kind: "slides", href: "assests/2026/CENG113M/LAB2/CENG113M_Lab2.pptx" },
      { label: "exercise_1_hello_world.py", kind: "code", href: "assests/2026/CENG113M/LAB2/exercise_1_hello_world.py" },
      { label: "exercise_2_temperature.py", kind: "code", href: "assests/2026/CENG113M/LAB2/exercise_2_temperature.py" },
      { label: "exercise_3_calculator.py", kind: "code", href: "assests/2026/CENG113M/LAB2/exercise_3_calculator.py" },
      { label: "exercise_4_pythagorean.py", kind: "code", href: "assests/2026/CENG113M/LAB2/exercise_4_pythagorean.py" },
      { label: "exercise_5_debug.py", kind: "code", href: "assests/2026/CENG113M/LAB2/exercise_5_debug.py" },
      { label: "exercise_6_string_inspector.py", kind: "code", href: "assests/2026/CENG113M/LAB2/exercise_6_string_inspector.py" },
      { label: "exercise_7_currency_converter.py", kind: "code", href: "assests/2026/CENG113M/LAB2/exercise_7_currency_converter.py" },
    ],
  },
  {
    year: "2026",
    course: "CENG113M",
    labDate: "LAB 3",
    title: "Lab 3",
    description: "Logic and decision-making practice files for Lab 3.",
    tags: ["python", "slides", "logic"],
    assets: [
      { label: "Lab 3 Logic & Decision Making.pptx", kind: "slides", href: "assests/2026/CENG113M/LAB3/Lab 3 Logic & Decision Making.pptx" },
      { label: "lab3.py", kind: "code", href: "assests/2026/CENG113M/LAB3/lab3.py" },
    ],
  },
  {
    year: "2026",
    course: "CENG113M",
    labDate: "LAB 4",
    title: "Lab 4",
    description: "Loop and control-flow exercises for Lab 4.",
    tags: ["python", "loops"],
    assets: [
      { label: "CENG113M_Lab4.pptx", kind: "slides", href: "assests/2026/CENG113M/LAB4/CENG113M_Lab4.pptx" },
      { label: "exercise1_count_up.py", kind: "code", href: "assests/2026/CENG113M/LAB4/exercise1_count_up.py" },
      { label: "exercise2_sum_of_numbers.py", kind: "code", href: "assests/2026/CENG113M/LAB4/exercise2_sum_of_numbers.py" },
      { label: "exercise3_countdown.py", kind: "code", href: "assests/2026/CENG113M/LAB4/exercise3_countdown.py" },
      { label: "exercise4_multiplication_table.py", kind: "code", href: "assests/2026/CENG113M/LAB4/exercise4_multiplication_table.py" },
      { label: "exercise5_guess_the_number.py", kind: "code", href: "assests/2026/CENG113M/LAB4/exercise5_guess_the_number.py" },
      { label: "exercise6_fizzbuzz.py", kind: "code", href: "assests/2026/CENG113M/LAB4/exercise6_fizzbuzz.py" },
      { label: "exercise7_sum_until_zero.py", kind: "code", href: "assests/2026/CENG113M/LAB4/exercise7_sum_until_zero.py" },
      { label: "exercise8_prime_checker.py", kind: "code", href: "assests/2026/CENG113M/LAB4/exercise8_prime_checker.py" },
      { label: "exercise9_skip_and_stop.py", kind: "code", href: "assests/2026/CENG113M/LAB4/exercise9_skip_and_stop.py" },
    ],
  },
  {
    year: "2026",
    course: "CENG113M",
    labDate: "LAB 5",
    title: "Lab 5",
    description: "Functions and practice scripts for Lab 5.",
    tags: ["python", "functions"],
    assets: [
      { label: "CENG113M Lab 5.pptx", kind: "slides", href: "assests/2026/CENG113M/LAB5/CENG113M Lab 5.pptx" },
      { label: "lab5.py", kind: "code", href: "assests/2026/CENG113M/LAB5/lab5.py" },
    ],
  },
  {
    year: "2026",
    course: "CENG113M",
    labDate: "LAB 6",
    title: "Lab 6",
    description: "Slides for Lab 6.",
    tags: ["slides"],
    assets: [
      { label: "CENG113M_Lab6.pptx", kind: "slides", href: "assests/2026/CENG113M/LAB6/CENG113M_Lab6.pptx" },
    ],
  },
  {
    year: "2026",
    course: "CENG113M",
    labDate: "LAB 7",
    title: "Lab 7",
    description: "Midterm Lab 7 practice files.",
    tags: ["python"],
    assets: [
      { label: "q2.py", kind: "code", href: "assests/2026/CENG113M/LAB7/q2.py" },
      { label: "q4.py", kind: "code", href: "assests/2026/CENG113M/LAB7/q4.py" },
    ],
  },
  {
    year: "2026",
    course: "CENG113M",
    labDate: "LAB 8",
    title: "Lab 8",
    description: "Lab 8 standard library exercises.",
    tags: ["python","standard library"],
    assets: [
      { label: "scores.txt", kind: "data", href: "assests/2026/CENG113M/LAB8/scores.txt" },
      { label: "server_log.txt", kind: "data", href: "assests/2026/CENG113M/LAB8/server_log.txt" },
      { label: "temperatures.txt", kind: "data", href: "assests/2026/CENG113M/LAB8/temperatures.txt" },
      { label: "words.txt", kind: "data", href: "assests/2026/CENG113M/LAB8/words.txt" },
    ],
  },
];